# Numpy 기초연습문제

In [1]:
import numpy as np


### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

`array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])
`

In [4]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [5]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [6]:
a[1, 2]


7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

`array([[5., 6., 7., 8.]])
`

In [7]:
a.shape


(3, 4)

In [8]:
a[[1], :]


array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

`array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])
`

In [9]:
a[:,[0, 2]]


array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

`array([1., 2., 3., 4., 5., 6.])
`

In [10]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [11]:
a[a <= 6]


array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [12]:
b = np.random.random((3, 4))
b

array([[0.52950395, 0.54456985, 0.94592257, 0.2758061 ],
       [0.61522849, 0.50632593, 0.76225256, 0.63018701],
       [0.13714025, 0.58098173, 0.94249791, 0.82184032]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [13]:
c = a * b
c

array([[ 0.52950395,  1.08913969,  2.83776771,  1.1032244 ],
       [ 3.07614245,  3.03795557,  5.33576792,  5.04149606],
       [ 1.23426221,  5.80981726, 10.36747696,  9.86208389]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [14]:
d = b.T
d

array([[0.52950395, 0.61522849, 0.13714025],
       [0.54456985, 0.50632593, 0.58098173],
       [0.94592257, 0.76225256, 0.94249791],
       [0.2758061 , 0.63018701, 0.82184032]])

In [15]:
d.shape


(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [16]:
print(a.shape, d.shape)


(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [17]:
e = a.dot(d)
e

array([[ 5.55963576,  6.43538606,  7.41395871],
       [14.74284564, 16.49136199, 17.34379951],
       [23.92605553, 26.54733793, 27.27364032]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [18]:
np.sum(e, axis=1)


array([19.40898052, 48.57800715, 77.74703378])